// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropertyLeasing.API.Data;

#nullable disable

namespace PropertyLeasingSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropertyLeasing.API.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<int?>("ApprovedByStaffId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId");

                    b.HasIndex("ApprovedByStaffId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UnitId");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            ApprovedByStaffId = 1,
                            Status = "Approved",
                            SubmittedAt = new DateTime(2026, 5, 6, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = 1,
                            UnitId = 2
                        });
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Lease", b =>
                {
                    b.Property<int>("LeaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaseId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("LeaseId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UnitId");

                    b.ToTable("Leases");

                    b.HasData(
                        new
                        {
                            LeaseId = 1,
                            ApplicationId = 1,
                            CreatedAt = new DateTime(2026, 5, 6, 22, 2, 37, 698, DateTimeKind.Local).AddTicks(637),
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyRent = 500.00m,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            TenantId = 1,
                            UnitId = 2
                        });
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.MaintenanceLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("WorkCompleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WorkStarted")
                        .HasColumnType("datetime2");

                    b.HasKey("LogId");

                    b.HasIndex("RequestId");

                    b.HasIndex("StaffId");

                    b.ToTable("MaintenanceLogs");

                    b.HasData(
                        new
                        {
                            LogId = 1,
                            ActionTaken = "Inspection started",
                            RequestId = 1,
                            StaffId = 2,
                            WorkStarted = new DateTime(2026, 5, 6, 22, 2, 37, 699, DateTimeKind.Local).AddTicks(5683)
                        });
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.MaintenanceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UnitId");

                    b.ToTable("MaintenanceRequests");

                    b.HasData(
                        new
                        {
                            RequestId = 1,
                            Description = "Air conditioner not working",
                            Priority = "High",
                            ReportedAt = new DateTime(2026, 5, 6, 22, 2, 37, 699, DateTimeKind.Local).AddTicks(4565),
                            Status = "Submitted",
                            TenantId = 1,
                            UnitId = 2
                        });
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LeaseId")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionTimestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentId");

                    b.HasIndex("LeaseId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 450m,
                            LeaseId = 1,
                            Method = "Cash",
                            PaymentDate = new DateTime(2026, 5, 6, 22, 2, 37, 699, DateTimeKind.Local).AddTicks(2604),
                            PaymentType = "Monthly Rent",
                            Status = "Paid",
                            TransactionTimestamp = new DateTime(2026, 5, 6, 22, 2, 37, 699, DateTimeKind.Local).AddTicks(2782)
                        });
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PropertyId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            PropertyId = 1,
                            Address = "Campus A",
                            City = "Isa Town",
                            ManagerId = 1,
                            PropertyName = "Bahrain Polytechnic",
                            PropertyType = "Residential"
                        });
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffId");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            StaffId = 1,
                            Email = "manager@test.com",
                            FullName = "Ahmed Ali",
                            HourlyRate = 25m,
                            RoleType = "Property Manager"
                        },
                        new
                        {
                            StaffId = 2,
                            Email = "maintenance@test.com",
                            FullName = "Ahmed Qusy",
                            HourlyRate = 15m,
                            RoleType = "Maintenance Staff"
                        });
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.StatusHistory", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.ToTable("StatusHistories");

                    b.HasData(
                        new
                        {
                            AuditId = 1,
                            ChangedAt = new DateTime(2026, 5, 6, 22, 2, 37, 699, DateTimeKind.Local).AddTicks(7090),
                            EntityId = 1,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Assigned",
                            OldStatus = "Submitted"
                        });
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantId = 1,
                            Email = "zahra@test.com",
                            FullName = "Zahra Almosawi",
                            Phone = "33334444"
                        },
                        new
                        {
                            TenantId = 2,
                            Email = "sarah@test.com",
                            FullName = "Sarah Ahmed",
                            Phone = "35556666"
                        });
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<decimal>("RentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            UnitId = 1,
                            Amenities = "Parking, WiFi",
                            IsAvailable = true,
                            PropertyId = 1,
                            RentAmount = 350m,
                            Size = "2 Bedroom",
                            UnitNumber = "A101"
                        },
                        new
                        {
                            UnitId = 2,
                            Amenities = "Parking, Pool",
                            IsAvailable = false,
                            PropertyId = 1,
                            RentAmount = 450m,
                            Size = "3 Bedroom",
                            UnitNumber = "A102"
                        });
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Application", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.Staff", "ApprovedByStaff")
                        .WithMany()
                        .HasForeignKey("ApprovedByStaffId");

                    b.HasOne("PropertyLeasing.API.Models.Tenant", "Tenant")
                        .WithMany("Applications")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyLeasing.API.Models.Unit", "Unit")
                        .WithMany("Applications")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByStaff");

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Lease", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyLeasing.API.Models.Tenant", "Tenant")
                        .WithMany("Leases")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyLeasing.API.Models.Unit", "Unit")
                        .WithMany("Leases")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.MaintenanceLog", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.MaintenanceRequest", "MaintenanceRequest")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyLeasing.API.Models.Staff", "Staff")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaintenanceRequest");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.MaintenanceRequest", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.Tenant", "Tenant")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyLeasing.API.Models.Unit", "Unit")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Payment", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.Lease", "Lease")
                        .WithMany("Payments")
                        .HasForeignKey("LeaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lease");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Property", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.Staff", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Unit", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.Property", "Property")
                        .WithMany("Units")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Lease", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.MaintenanceRequest", b =>
                {
                    b.Navigation("MaintenanceLogs");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Property", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Staff", b =>
                {
                    b.Navigation("MaintenanceLogs");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Tenant", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Leases");

                    b.Navigation("MaintenanceRequests");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Unit", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Leases");

                    b.Navigation("MaintenanceRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
