// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropertyLeasing.API.Data;

#nullable disable

namespace PropertyLeasing.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260507001440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<int?>("ApprovedByStaffId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId");

                    b.HasIndex("ApprovedByStaffId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UnitId");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            ApprovedByStaffId = 1,
                            ProcessedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "LeaseActive",
                            SubmittedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = 1,
                            UnitId = 2
                        },
                        new
                        {
                            ApplicationId = 2,
                            ApprovedByStaffId = 1,
                            ProcessedAt = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "LeaseActive",
                            SubmittedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = 2,
                            UnitId = 5
                        },
                        new
                        {
                            ApplicationId = 3,
                            ApprovedByStaffId = 1,
                            ProcessedAt = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "LeaseActive",
                            SubmittedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = 3,
                            UnitId = 3
                        },
                        new
                        {
                            ApplicationId = 4,
                            ApprovedByStaffId = 1,
                            ProcessedAt = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "LeaseActive",
                            SubmittedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = 4,
                            UnitId = 8
                        },
                        new
                        {
                            ApplicationId = 5,
                            Status = "Submitted",
                            SubmittedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = 2,
                            UnitId = 6
                        },
                        new
                        {
                            ApplicationId = 6,
                            Status = "Screening",
                            SubmittedAt = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = 3,
                            UnitId = 7
                        },
                        new
                        {
                            ApplicationId = 7,
                            ProcessedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Rejected",
                            SubmittedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = 1,
                            UnitId = 9
                        });
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Lease", b =>
                {
                    b.Property<int>("LeaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaseId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("LeaseId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UnitId");

                    b.ToTable("Leases");

                    b.HasData(
                        new
                        {
                            LeaseId = 1,
                            ApplicationId = 1,
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyRent = 450m,
                            StartDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "LeaseActive",
                            TenantId = 1,
                            UnitId = 2
                        },
                        new
                        {
                            LeaseId = 2,
                            ApplicationId = 2,
                            CreatedAt = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyRent = 700m,
                            StartDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "LeaseActive",
                            TenantId = 2,
                            UnitId = 5
                        },
                        new
                        {
                            LeaseId = 3,
                            ApplicationId = 3,
                            CreatedAt = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyRent = 550m,
                            StartDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "LeaseActive",
                            TenantId = 3,
                            UnitId = 3
                        },
                        new
                        {
                            LeaseId = 4,
                            ApplicationId = 4,
                            CreatedAt = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlyRent = 1200m,
                            StartDate = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "LeaseActive",
                            TenantId = 4,
                            UnitId = 8
                        });
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.MaintenanceLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("WorkCompleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WorkStarted")
                        .HasColumnType("datetime2");

                    b.HasKey("LogId");

                    b.HasIndex("RequestId");

                    b.HasIndex("StaffId");

                    b.ToTable("MaintenanceLogs");

                    b.HasData(
                        new
                        {
                            LogId = 1,
                            ActionTaken = "Inspected AC unit — refrigerant recharge needed",
                            RequestId = 1,
                            StaffId = 4,
                            WorkCompleted = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkStarted = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LogId = 2,
                            ActionTaken = "Recharged refrigerant and tested cooling",
                            RequestId = 1,
                            StaffId = 4,
                            WorkCompleted = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkStarted = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LogId = 3,
                            ActionTaken = "Replaced faulty pipe connector under sink",
                            RequestId = 2,
                            StaffId = 2,
                            WorkCompleted = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkStarted = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LogId = 4,
                            ActionTaken = "Replaced flickering bulb and inspected wiring",
                            RequestId = 3,
                            StaffId = 3,
                            WorkCompleted = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkStarted = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LogId = 5,
                            ActionTaken = "Inspected window — replacement latch ordered",
                            RequestId = 4,
                            StaffId = 2,
                            WorkStarted = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LogId = 6,
                            ActionTaken = "Lubricated and realigned door lock mechanism",
                            RequestId = 8,
                            StaffId = 2,
                            WorkCompleted = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkStarted = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LogId = 7,
                            ActionTaken = "Replaced capacitor on ceiling fan motor",
                            RequestId = 9,
                            StaffId = 3,
                            WorkCompleted = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkStarted = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LogId = 8,
                            ActionTaken = "Replaced faulty thermostat on water heater",
                            RequestId = 10,
                            StaffId = 3,
                            WorkCompleted = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkStarted = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LogId = 9,
                            ActionTaken = "Cleared blockage using drain snake tool",
                            RequestId = 11,
                            StaffId = 2,
                            WorkCompleted = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkStarted = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LogId = 10,
                            ActionTaken = "Replaced broken double socket and tested circuit",
                            RequestId = 12,
                            StaffId = 3,
                            WorkCompleted = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkStarted = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LogId = 11,
                            ActionTaken = "Assessed door track — new roller kit required",
                            RequestId = 13,
                            StaffId = 2,
                            WorkStarted = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LogId = 12,
                            ActionTaken = "Inspected ductwork — damper adjustment in progress",
                            RequestId = 14,
                            StaffId = 4,
                            WorkStarted = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.MaintenanceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int?>("AssignedStaffId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("AssignedStaffId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UnitId");

                    b.ToTable("MaintenanceRequests");

                    b.HasData(
                        new
                        {
                            RequestId = 1,
                            AssignedStaffId = 4,
                            Description = "Air conditioner not cooling properly",
                            Priority = "High",
                            ReportedAt = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Closed",
                            TenantId = 1,
                            UnitId = 2
                        },
                        new
                        {
                            RequestId = 2,
                            AssignedStaffId = 2,
                            Description = "Kitchen sink is leaking",
                            Priority = "Medium",
                            ReportedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Closed",
                            TenantId = 1,
                            UnitId = 2
                        },
                        new
                        {
                            RequestId = 8,
                            AssignedStaffId = 2,
                            Description = "Front door lock is jammed",
                            Priority = "High",
                            ReportedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Closed",
                            TenantId = 3,
                            UnitId = 3
                        },
                        new
                        {
                            RequestId = 9,
                            AssignedStaffId = 3,
                            Description = "Office ceiling fan stopped working",
                            Priority = "Low",
                            ReportedAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Closed",
                            TenantId = 4,
                            UnitId = 8
                        },
                        new
                        {
                            RequestId = 10,
                            AssignedStaffId = 3,
                            Description = "Water heater tripping the circuit breaker",
                            Priority = "High",
                            ReportedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Closed",
                            TenantId = 2,
                            UnitId = 5
                        },
                        new
                        {
                            RequestId = 3,
                            AssignedStaffId = 3,
                            Description = "Bathroom light flickering",
                            Priority = "Low",
                            ReportedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Resolved",
                            TenantId = 2,
                            UnitId = 5
                        },
                        new
                        {
                            RequestId = 11,
                            AssignedStaffId = 2,
                            Description = "Shower drain is blocked",
                            Priority = "Medium",
                            ReportedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Resolved",
                            TenantId = 3,
                            UnitId = 3
                        },
                        new
                        {
                            RequestId = 12,
                            AssignedStaffId = 3,
                            Description = "Broken socket in meeting room",
                            Priority = "Medium",
                            ReportedAt = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Resolved",
                            TenantId = 4,
                            UnitId = 8
                        },
                        new
                        {
                            RequestId = 4,
                            AssignedStaffId = 2,
                            Description = "Broken window latch in bedroom",
                            Priority = "Medium",
                            ReportedAt = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            TenantId = 3,
                            UnitId = 3
                        },
                        new
                        {
                            RequestId = 13,
                            AssignedStaffId = 2,
                            Description = "Balcony sliding door off its track",
                            Priority = "Medium",
                            ReportedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            TenantId = 1,
                            UnitId = 2
                        },
                        new
                        {
                            RequestId = 14,
                            AssignedStaffId = 4,
                            Description = "Air duct making whistling sound",
                            Priority = "Low",
                            ReportedAt = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            TenantId = 4,
                            UnitId = 8
                        },
                        new
                        {
                            RequestId = 5,
                            AssignedStaffId = 4,
                            Description = "HVAC system making loud noise",
                            Priority = "High",
                            ReportedAt = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Assigned",
                            TenantId = 4,
                            UnitId = 8
                        },
                        new
                        {
                            RequestId = 15,
                            AssignedStaffId = 3,
                            Description = "Kitchen exhaust fan not working",
                            Priority = "Low",
                            ReportedAt = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Assigned",
                            TenantId = 2,
                            UnitId = 5
                        },
                        new
                        {
                            RequestId = 16,
                            AssignedStaffId = 2,
                            Description = "Bedroom wardrobe door hinge broken",
                            Priority = "Low",
                            ReportedAt = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Assigned",
                            TenantId = 3,
                            UnitId = 3
                        },
                        new
                        {
                            RequestId = 6,
                            Description = "Hot water not working in the morning",
                            Priority = "High",
                            ReportedAt = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Submitted",
                            TenantId = 1,
                            UnitId = 2
                        },
                        new
                        {
                            RequestId = 7,
                            Description = "Paint peeling off living room wall",
                            Priority = "Low",
                            ReportedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Submitted",
                            TenantId = 2,
                            UnitId = 5
                        },
                        new
                        {
                            RequestId = 17,
                            Description = "Main entrance door closer needs adjustment",
                            Priority = "Medium",
                            ReportedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Submitted",
                            TenantId = 4,
                            UnitId = 8
                        },
                        new
                        {
                            RequestId = 18,
                            Description = "Cockroach infestation in kitchen area",
                            Priority = "High",
                            ReportedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Submitted",
                            TenantId = 3,
                            UnitId = 3
                        },
                        new
                        {
                            RequestId = 19,
                            Description = "Bedroom ceiling has water stain — possible leak",
                            Priority = "High",
                            ReportedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Submitted",
                            TenantId = 1,
                            UnitId = 2
                        });
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LeaseId")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionTimestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentId");

                    b.HasIndex("LeaseId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 450m,
                            LeaseId = 1,
                            Method = "Bank Transfer",
                            PaymentDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentType = "Monthly Rent",
                            Status = "Paid",
                            TransactionTimestamp = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 450m,
                            LeaseId = 1,
                            Method = "Bank Transfer",
                            PaymentDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentType = "Monthly Rent",
                            Status = "Paid",
                            TransactionTimestamp = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentId = 3,
                            Amount = 450m,
                            LeaseId = 1,
                            Method = "Cash",
                            PaymentDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentType = "Monthly Rent",
                            Status = "Paid",
                            TransactionTimestamp = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentId = 4,
                            Amount = 450m,
                            LeaseId = 1,
                            Method = "Cash",
                            PaymentDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentType = "Monthly Rent",
                            Status = "Overdue",
                            TransactionTimestamp = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentId = 5,
                            Amount = 700m,
                            LeaseId = 2,
                            Method = "Bank Transfer",
                            PaymentDate = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentType = "Monthly Rent",
                            Status = "Paid",
                            TransactionTimestamp = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentId = 6,
                            Amount = 700m,
                            LeaseId = 2,
                            Method = "Bank Transfer",
                            PaymentDate = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentType = "Monthly Rent",
                            Status = "Paid",
                            TransactionTimestamp = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentId = 7,
                            Amount = 700m,
                            LeaseId = 2,
                            Method = "Online",
                            PaymentDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentType = "Monthly Rent",
                            Status = "Paid",
                            TransactionTimestamp = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentId = 8,
                            Amount = 550m,
                            LeaseId = 3,
                            Method = "Cheque",
                            PaymentDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentType = "Monthly Rent",
                            Status = "Paid",
                            TransactionTimestamp = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentId = 9,
                            Amount = 550m,
                            LeaseId = 3,
                            Method = "Cheque",
                            PaymentDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentType = "Monthly Rent",
                            Status = "Paid",
                            TransactionTimestamp = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentId = 10,
                            Amount = 550m,
                            LeaseId = 3,
                            Method = "Bank Transfer",
                            PaymentDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentType = "Monthly Rent",
                            Status = "Overdue",
                            TransactionTimestamp = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentId = 11,
                            Amount = 1200m,
                            LeaseId = 4,
                            Method = "Bank Transfer",
                            PaymentDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentType = "Monthly Rent",
                            Status = "Paid",
                            TransactionTimestamp = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentId = 12,
                            Amount = 1200m,
                            LeaseId = 4,
                            Method = "Bank Transfer",
                            PaymentDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentType = "Monthly Rent",
                            Status = "Paid",
                            TransactionTimestamp = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PropertyId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            PropertyId = 1,
                            Address = "Campus A",
                            City = "Isa Town",
                            ManagerId = 1,
                            PropertyName = "Bahrain Polytechnic Residences",
                            PropertyType = "Residential"
                        },
                        new
                        {
                            PropertyId = 2,
                            Address = "Seef District",
                            City = "Manama",
                            ManagerId = 1,
                            PropertyName = "Seef Pearl Towers",
                            PropertyType = "Residential"
                        },
                        new
                        {
                            PropertyId = 3,
                            Address = "Riffa Main Road",
                            City = "Riffa",
                            ManagerId = 1,
                            PropertyName = "Riffa Business Park",
                            PropertyType = "Commercial"
                        });
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffId");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            StaffId = 1,
                            Email = "manager@test.com",
                            FullName = "Ahmed Ali",
                            HourlyRate = 25m,
                            IsAvailable = true,
                            RoleType = "Property Manager",
                            SkillType = "Management"
                        },
                        new
                        {
                            StaffId = 2,
                            Email = "maintenance@test.com",
                            FullName = "Ahmed Qusy",
                            HourlyRate = 15m,
                            IsAvailable = true,
                            RoleType = "Maintenance Staff",
                            SkillType = "Plumbing"
                        },
                        new
                        {
                            StaffId = 3,
                            Email = "khalid@test.com",
                            FullName = "Khalid Nasser",
                            HourlyRate = 18m,
                            IsAvailable = true,
                            RoleType = "Maintenance Staff",
                            SkillType = "Electrical"
                        },
                        new
                        {
                            StaffId = 4,
                            Email = "fatima@test.com",
                            FullName = "Fatima Hassan",
                            HourlyRate = 16m,
                            IsAvailable = false,
                            RoleType = "Maintenance Staff",
                            SkillType = "HVAC"
                        });
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.StatusHistory", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.ToTable("StatusHistories");

                    b.HasData(
                        new
                        {
                            AuditId = 1,
                            ChangedAt = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 1,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Assigned",
                            OldStatus = "Submitted"
                        },
                        new
                        {
                            AuditId = 2,
                            ChangedAt = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 1,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "InProgress",
                            OldStatus = "Assigned"
                        },
                        new
                        {
                            AuditId = 3,
                            ChangedAt = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 1,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Resolved",
                            OldStatus = "InProgress"
                        },
                        new
                        {
                            AuditId = 4,
                            ChangedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 1,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Closed",
                            OldStatus = "Resolved"
                        },
                        new
                        {
                            AuditId = 5,
                            ChangedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 2,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Assigned",
                            OldStatus = "Submitted"
                        },
                        new
                        {
                            AuditId = 6,
                            ChangedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 2,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "InProgress",
                            OldStatus = "Assigned"
                        },
                        new
                        {
                            AuditId = 7,
                            ChangedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 2,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Resolved",
                            OldStatus = "InProgress"
                        },
                        new
                        {
                            AuditId = 8,
                            ChangedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 3,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Assigned",
                            OldStatus = "Submitted"
                        },
                        new
                        {
                            AuditId = 9,
                            ChangedAt = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 3,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "InProgress",
                            OldStatus = "Assigned"
                        },
                        new
                        {
                            AuditId = 10,
                            ChangedAt = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 4,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Assigned",
                            OldStatus = "Submitted"
                        },
                        new
                        {
                            AuditId = 16,
                            ChangedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 8,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Assigned",
                            OldStatus = "Submitted"
                        },
                        new
                        {
                            AuditId = 17,
                            ChangedAt = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 8,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "InProgress",
                            OldStatus = "Assigned"
                        },
                        new
                        {
                            AuditId = 18,
                            ChangedAt = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 8,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Resolved",
                            OldStatus = "InProgress"
                        },
                        new
                        {
                            AuditId = 19,
                            ChangedAt = new DateTime(2026, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 8,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Closed",
                            OldStatus = "Resolved"
                        },
                        new
                        {
                            AuditId = 20,
                            ChangedAt = new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 9,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Assigned",
                            OldStatus = "Submitted"
                        },
                        new
                        {
                            AuditId = 21,
                            ChangedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 9,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "InProgress",
                            OldStatus = "Assigned"
                        },
                        new
                        {
                            AuditId = 22,
                            ChangedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 9,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Resolved",
                            OldStatus = "InProgress"
                        },
                        new
                        {
                            AuditId = 23,
                            ChangedAt = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 9,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Closed",
                            OldStatus = "Resolved"
                        },
                        new
                        {
                            AuditId = 24,
                            ChangedAt = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 10,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Assigned",
                            OldStatus = "Submitted"
                        },
                        new
                        {
                            AuditId = 25,
                            ChangedAt = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 10,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "InProgress",
                            OldStatus = "Assigned"
                        },
                        new
                        {
                            AuditId = 26,
                            ChangedAt = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 10,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Resolved",
                            OldStatus = "InProgress"
                        },
                        new
                        {
                            AuditId = 27,
                            ChangedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 10,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Closed",
                            OldStatus = "Resolved"
                        },
                        new
                        {
                            AuditId = 28,
                            ChangedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 11,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Assigned",
                            OldStatus = "Submitted"
                        },
                        new
                        {
                            AuditId = 29,
                            ChangedAt = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 11,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "InProgress",
                            OldStatus = "Assigned"
                        },
                        new
                        {
                            AuditId = 30,
                            ChangedAt = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 11,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Resolved",
                            OldStatus = "InProgress"
                        },
                        new
                        {
                            AuditId = 31,
                            ChangedAt = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 12,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Assigned",
                            OldStatus = "Submitted"
                        },
                        new
                        {
                            AuditId = 32,
                            ChangedAt = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 12,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "InProgress",
                            OldStatus = "Assigned"
                        },
                        new
                        {
                            AuditId = 33,
                            ChangedAt = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 12,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Resolved",
                            OldStatus = "InProgress"
                        },
                        new
                        {
                            AuditId = 34,
                            ChangedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 13,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Assigned",
                            OldStatus = "Submitted"
                        },
                        new
                        {
                            AuditId = 35,
                            ChangedAt = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 13,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "InProgress",
                            OldStatus = "Assigned"
                        },
                        new
                        {
                            AuditId = 36,
                            ChangedAt = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 14,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Assigned",
                            OldStatus = "Submitted"
                        },
                        new
                        {
                            AuditId = 37,
                            ChangedAt = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 14,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "InProgress",
                            OldStatus = "Assigned"
                        },
                        new
                        {
                            AuditId = 38,
                            ChangedAt = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 15,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Assigned",
                            OldStatus = "Submitted"
                        },
                        new
                        {
                            AuditId = 39,
                            ChangedAt = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 16,
                            EntityName = "MaintenanceRequest",
                            NewStatus = "Assigned",
                            OldStatus = "Submitted"
                        },
                        new
                        {
                            AuditId = 11,
                            ChangedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 1,
                            EntityName = "Application",
                            NewStatus = "Screening",
                            OldStatus = "Submitted"
                        },
                        new
                        {
                            AuditId = 12,
                            ChangedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 1,
                            EntityName = "Application",
                            NewStatus = "Approved",
                            OldStatus = "Screening"
                        },
                        new
                        {
                            AuditId = 13,
                            ChangedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 1,
                            EntityName = "Application",
                            NewStatus = "LeaseActive",
                            OldStatus = "Approved"
                        },
                        new
                        {
                            AuditId = 14,
                            ChangedAt = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 7,
                            EntityName = "Application",
                            NewStatus = "Screening",
                            OldStatus = "Submitted"
                        },
                        new
                        {
                            AuditId = 15,
                            ChangedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EntityId = 7,
                            EntityName = "Application",
                            NewStatus = "Rejected",
                            OldStatus = "Screening"
                        });
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantId = 1,
                            Email = "zahra@test.com",
                            FullName = "Zahra Almosawi",
                            Phone = "33334444"
                        },
                        new
                        {
                            TenantId = 2,
                            Email = "sarah@test.com",
                            FullName = "Sarah Ahmed",
                            Phone = "35556666"
                        },
                        new
                        {
                            TenantId = 3,
                            Email = "omar@test.com",
                            FullName = "Omar Khalil",
                            Phone = "39998888"
                        },
                        new
                        {
                            TenantId = 4,
                            Email = "noura@test.com",
                            FullName = "Noura Jassim",
                            Phone = "36667777"
                        });
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<decimal>("RentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            UnitId = 1,
                            Amenities = "WiFi, Parking",
                            IsAvailable = true,
                            PropertyId = 1,
                            RentAmount = 350m,
                            Size = "1 Bedroom",
                            UnitNumber = "A101"
                        },
                        new
                        {
                            UnitId = 2,
                            Amenities = "WiFi, Parking, Pool",
                            IsAvailable = false,
                            PropertyId = 1,
                            RentAmount = 450m,
                            Size = "2 Bedroom",
                            UnitNumber = "A102"
                        },
                        new
                        {
                            UnitId = 3,
                            Amenities = "WiFi, Parking, Gym",
                            IsAvailable = false,
                            PropertyId = 1,
                            RentAmount = 550m,
                            Size = "3 Bedroom",
                            UnitNumber = "A103"
                        },
                        new
                        {
                            UnitId = 4,
                            Amenities = "WiFi",
                            IsAvailable = true,
                            PropertyId = 1,
                            RentAmount = 300m,
                            Size = "Studio",
                            UnitNumber = "A104"
                        },
                        new
                        {
                            UnitId = 5,
                            Amenities = "WiFi, Sea View, Gym",
                            IsAvailable = false,
                            PropertyId = 2,
                            RentAmount = 700m,
                            Size = "2 Bedroom",
                            UnitNumber = "T101"
                        },
                        new
                        {
                            UnitId = 6,
                            Amenities = "WiFi, Sea View, Pool, Gym",
                            IsAvailable = true,
                            PropertyId = 2,
                            RentAmount = 900m,
                            Size = "3 Bedroom",
                            UnitNumber = "T102"
                        },
                        new
                        {
                            UnitId = 7,
                            Amenities = "WiFi, Balcony",
                            IsAvailable = true,
                            PropertyId = 2,
                            RentAmount = 500m,
                            Size = "1 Bedroom",
                            UnitNumber = "T103"
                        },
                        new
                        {
                            UnitId = 8,
                            Amenities = "Parking, Security",
                            IsAvailable = false,
                            PropertyId = 3,
                            RentAmount = 1200m,
                            Size = "Office",
                            UnitNumber = "B201"
                        },
                        new
                        {
                            UnitId = 9,
                            Amenities = "Parking",
                            IsAvailable = true,
                            PropertyId = 3,
                            RentAmount = 800m,
                            Size = "Office",
                            UnitNumber = "B202"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyLeasing.API.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Application", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.Staff", "ApprovedByStaff")
                        .WithMany()
                        .HasForeignKey("ApprovedByStaffId");

                    b.HasOne("PropertyLeasing.API.Models.Tenant", "Tenant")
                        .WithMany("Applications")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyLeasing.API.Models.Unit", "Unit")
                        .WithMany("Applications")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByStaff");

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Lease", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyLeasing.API.Models.Tenant", "Tenant")
                        .WithMany("Leases")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyLeasing.API.Models.Unit", "Unit")
                        .WithMany("Leases")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.MaintenanceLog", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.MaintenanceRequest", "MaintenanceRequest")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyLeasing.API.Models.Staff", "Staff")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaintenanceRequest");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.MaintenanceRequest", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.Staff", "AssignedStaff")
                        .WithMany()
                        .HasForeignKey("AssignedStaffId");

                    b.HasOne("PropertyLeasing.API.Models.Tenant", "Tenant")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyLeasing.API.Models.Unit", "Unit")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedStaff");

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Payment", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.Lease", "Lease")
                        .WithMany("Payments")
                        .HasForeignKey("LeaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lease");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Property", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.Staff", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Unit", b =>
                {
                    b.HasOne("PropertyLeasing.API.Models.Property", "Property")
                        .WithMany("Units")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Lease", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.MaintenanceRequest", b =>
                {
                    b.Navigation("MaintenanceLogs");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Property", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Staff", b =>
                {
                    b.Navigation("MaintenanceLogs");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Tenant", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Leases");

                    b.Navigation("MaintenanceRequests");
                });

            modelBuilder.Entity("PropertyLeasing.API.Models.Unit", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Leases");

                    b.Navigation("MaintenanceRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
